#! /bin/sh

#codons="TTTTTCTTATTGCTTCTCCTACTGATTATCATAATGGGTGTCGTAGTGTCTTCCTCATCGCCTCCC
#CCACCGACTACCACAACGGCTGCCGCAGCGTATTACCATCACCAACAGAATAACAAAAAGGATGAC
#GAAGAGTGTTGCTGGCGTCGCCGACGGAGTAGCAGAAGGGGTGGCGGAGGG"


sed -e '/TAA/{N; s/TAA\n/TTTTTCTTATTGCTTCTCCTACTGATTATCATAATGGGTGTCGTAGTGTCTTCCTCATCGCCTCCCCCACCGACTACCACAACGGCTGCCGCAGCGTATTACCATCACCAACAGAATAACAAAAAGGATGACGAAGAGTGTTGCTGGCGTCGCCGACGGAGTAGCAGAAGGGGTGGCGGAGGGTAA\n/ }' -i ../data/testGenome.fasta
sed -e '/TGA/{N; s/TGA\n/TTTTTCTTATTGCTTCTCCTACTGATTATCATAATGGGTGTCGTAGTGTCTTCCTCATCGCCTCCCCCACCGACTACCACAACGGCTGCCGCAGCGTATTACCATCACCAACAGAATAACAAAAAGGATGACGAAGAGTGTTGCTGGCGTCGCCGACGGAGTAGCAGAAGGGGTGGCGGAGGGTGA\n/ }' -i ../data/testGenome.fasta
sed -e '/TAG/{N; s/TAG\n/TTTTTCTTATTGCTTCTCCTACTGATTATCATAATGGGTGTCGTAGTGTCTTCCTCATCGCCTCCCCCACCGACTACCACAACGGCTGCCGCAGCGTATTACCATCACCAACAGAATAACAAAAAGGATGACGAAGAGTGTTGCTGGCGTCGCCGACGGAGTAGCAGAAGGGGTGGCGGAGGGTAG\n/ }' -i ../data/testGenome.fasta

